language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -r requirements.txt"
script:
  - coverage run --source usabilla.py tests.py
after_success:
  - coveralls
deploy:
  provider: pypi
  user: usabilla
  password:
    secure: "GZSMtc3Srg2rkfuJJAqKLPTrN6ftrX+qTYwDGbhsWTuB5ORtfxvUDX8PfuJBtR9nbO60F16wRUYQ4SziGftvnS+mFvAeSVsLbs5plnrY3cnwTM8H5Ixp9q0+BUHSQ6YWeZnDkJSaSOH9+0MbHqYmP6L7ExOo1OYQ4D7yAQHCNmI="
  on:
    tags: true
    repo: usabilla/api-python
