language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -r requirements.txt"
script:
  - coverage run --source usabilla.py tests.py
after_success:
  - coveralls
deploy:
  provider: pypi
  user: usabilla
  password:
    secure: b+LpGmyPqGCgIM4xYx44Pnggm9Z628mIahwEJF7879MKB1845enL0EaaUQhvNv/UKd+/wpM6/yl2BbA2ojzK+Aikx3jZLtOnluQ/S/yKXB66vuzMnXDnRJQFxk0s/cvy/xJHVVbXOM5BlWPzgBrkkJa1hEa8TdBcuKhCi9cbc10=
  on:
    tags: true
    repo: usabilla/api-python
