language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -r requirements.txt"
script:
  - coverage run --source usabilla.py tests.py
after_success:
  - coveralls
deploy:
  provider: pypi
  user: usabilla
  password:
    secure: "OpnOWdmWnTKE1MBj6XloQso+FvHMgAuNjd5mbf1+4+WqzrZRJsiq6V4eSLwuZR7ppGiYJ9P87zj2xf6WZvJ5LjGE/jAgB2CU6gfqTSGGcvJgzhYn04e478Ix9qannV2CG28duqo3B21bHfXSHf9H2lXCiG692ouYRYucKDVGEwQ="
  on:
    tags: true
    repo: usabilla/api-python
