language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -r requirements.txt"
script:
  - coverage run --source usabilla.py tests.py
after_success:
  - coveralls
deploy:
  provider: pypi
  user: usabilla
  password:
    secure: poQGN/pM1rkT7PfvO64PIPwwTAkJxeJcfRPUFOyaeQTGhL0Xmc4J9XcHg+wx1vSKdtX7ioYW70YD4J+24np8nAWHAwZ7zf5MecWEvxAucGeBf5bESTxzU+FWYzH+YjHSFsmc5N9A83S4dY+JK3JlEooNRa6l6XqDUBa+9LHzi/k=
  on:
    tags: true
    repo: usabilla/api-python
